version: 0.2
env:
  variables:
    CI: "true"
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm ci
  build:
    commands:
      # - npm test
      - npm run build

      - |
        aws s3 sync \
          --cache-control='max-age=604800' \
          --exclude=index.html \
          build/ s3://library.sourceallies.com
      - |
        aws s3 sync \
          --cache-control='no-cache' \
          --include=index.html \
          --exclude='*' \
          build/ s3://$BUCKET_NAME
artifacts:
  base-directory: build
  files:
    - '**/*'