version = 0.1

[dev.deploy.parameters]
stack_name = "sai-librarian"
resolve_s3 = true
s3_prefix = "sai-librarian"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
fail_on_empty_changeset = false
parameter_overrides = [
    "DomainName=library.dev.sourceallies.com", 
    "HostedZoneId=Z2LBG8W17PXZI7",
    "OpenIdAud=242865329519-oa7lva9ueokgomi7ehlrdk0meuvu9nfb.apps.googleusercontent.com"
]

[prod.deploy.parameters]
stack_name = "sai-librarian"
resolve_s3 = true
s3_prefix = "sai-librarian"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
fail_on_empty_changeset = false
parameter_overrides = [
    "DomainName=library.sourceallies.com", 
    "HostedZoneId=Z8S32S7A9WVD6",
    "OpenIdAud=242865329519-oa7lva9ueokgomi7ehlrdk0meuvu9nfb.apps.googleusercontent.com"
]

