Description: sai-librarian
Parameters:
  DomainName:
    Type: String
    Default: library.sourceallies.com
Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName