name: Main Pipeline
on: 
  push:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

      - name: Unit Tests
        run: npm test

  deploy-dev:
    needs: verify
    runs-on: ubuntu-latest
    concurrency: deploy-dev
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::729161019481:role/Deployer"
          role-session-name: DeployToDev

      - name: Deploy Cloudformation
        run: sam deploy --config-env=dev

      - name: Build
        env:
          REACT_APP_ROLE_ARN: "arn:aws:iam::729161019481:role/sai-librarian-user"
        run: npm run build

      - name: Upload to S3
        working-directory: build
        run: aws s3 sync . s3://library.dev.sourceallies.com

  deploy-prod:
    needs: deploy-dev
    runs-on: ubuntu-latest
    concurrency: deploy-prod
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::487696863217:role/Deployer"
          role-session-name: DeployToProd

      - name: Deploy Cloudformation
        run: sam deploy --config-env=prod

      - name: Build
        env:
          REACT_APP_ROLE_ARN: "arn:aws:iam::487696863217:role/sai-librarian-user"
        run: npm run build

      - name: Upload to S3
        working-directory: build
        run: aws s3 sync . s3://library.sourceallies.com
