name: PR Verify
on: 
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

      - name: Unit Tests
        run: npm test