name: PR Verify
on: 
  pull_request:
    branches:
      - master
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run eslint

      - name: Unit Tests
        run: npm test

  create-changesets:
    runs-on: ubuntu-latest
    concurrency: "deploy-${{ matrix.env }}"
    strategy:
      matrix:
        env:
          - dev
          - prod
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      
      - name: Install Dependencies
        run: npm ci

      - uses: aws-actions/setup-sam@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          role-to-assume: "arn:aws:iam::729161019481:role/Deployer"
          role-session-name: CreateChangeset

      - name: Deploy Cloudformation
        run: sam deploy --config-env=${{ matrix.env }} --no-execute-changeset
